spring:
  application:
    name: eventos-api

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}

  flyway:
    enabled: false
    baseline-on-migrate: false
    validate-on-migrate: true
    out-of-order: false
    baseline-version: 0
    baseline-description: Baseline for existing database

  web:
    error:
      include-stacktrace: never

api:
  security:
    token:
        secret: ${JWT_SECRET:my-secret-key}